const CAMPING = {
  "name": "Camping du Pont, Pradons",
  "lat": 44.482,
  "lon": 4.359
};
const ACTIVITIES = [
  {
    "title": "Rivierstrand bij Camping du Pont",
    "type": [
      "Water",
      "Zwemmen",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 0,
    "duration": "1 uur",
    "distance": "0 km",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.482,
    "lon": 4.359,
    "photo": "ardeche river swimming family",
    "desc": "Makkelijkste daginvulling: zwemmen, dammetjes bouwen, schepnet mee en later weer terug naar de tent.",
    "link": "https://www.campingdupontardeche.com/le-camping/",
    "id": "a001",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.482,4.359",
    "photo_url": "https://source.unsplash.com/800x520/?ardeche%20river%20swimming%20family",
    "top": true,
    "mainCat": "water",
    "combine": [],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Cirque de Gens korte lus",
    "type": [
      "Wandelen",
      "Uitzicht",
      "Dichtbij"
    ],
    "age": 5,
    "height": "",
    "drive": 5,
    "duration": "1-2 uur",
    "distance": "3-5 km wandelen",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": false,
    "rain": false,
    "lat": 44.489,
    "lon": 4.372,
    "photo": "Cirque de Gens Ardeche",
    "desc": "Een van de mooiste korte wandelingen vlakbij de camping. Let op bij klifranden met jonge kinderen.",
    "link": "https://www.google.com/search?q=Cirque+de+Gens+wandeling+Ruoms",
    "id": "a002",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.489,4.372",
    "photo_url": "https://source.unsplash.com/800x520/?Cirque%20de%20Gens%20Ardeche",
    "top": true,
    "mainCat": "walk",
    "combine": [
      "Cirque de Gens korte lus",
      "Ruoms oude centrum + ijsje",
      "Via Ardèche - stukje fietsen vanaf Ruoms"
    ],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Ruoms oude centrum + ijsje",
    "type": [
      "Dorpjes",
      "Eten",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 7,
    "duration": "1-2 uur",
    "distance": "6 km",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "Ruoms Ardeche village",
    "desc": "Laagdrempelig avondrondje: straatjes, winkeltjes, markt/terras en een ijsje.",
    "link": "https://www.google.com/search?q=Ruoms+Ardeche+markt+oude+centrum",
    "id": "a003",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?Ruoms%20Ardeche%20village",
    "top": false,
    "mainCat": "culture",
    "combine": [
      "Cirque de Gens korte lus",
      "Ruoms oude centrum + ijsje",
      "Via Ardèche - stukje fietsen vanaf Ruoms"
    ],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Via Ardèche - stukje fietsen vanaf Ruoms",
    "type": [
      "Fietsen",
      "Kindvriendelijk",
      "Dichtbij"
    ],
    "age": 5,
    "height": "Zelfstandig kunnen fietsen",
    "drive": 8,
    "duration": "1-3 uur",
    "distance": "zelf kiezen",
    "difficulty": 1,
    "cost": "Gratis/fietshuur",
    "heat": true,
    "rain": false,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "voie verte ardeche cycling family",
    "desc": "Autoluwe/veilige fietsroute over oude spoortracés. Kies een kort stuk voor Kato/Rover en keer om wanneer het genoeg is.",
    "link": "https://via-ardeche.fr/",
    "id": "a004",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?voie%20verte%20ardeche%20cycling%20family",
    "top": true,
    "mainCat": "bike",
    "combine": [
      "Cirque de Gens korte lus",
      "Ruoms oude centrum + ijsje",
      "Via Ardèche - stukje fietsen vanaf Ruoms"
    ],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Balazuc + rivierstrand",
    "type": [
      "Dorpjes",
      "Zwemmen",
      "Wandelen"
    ],
    "age": 0,
    "height": "",
    "drive": 12,
    "duration": "Halve dag",
    "distance": "2-4 km slenteren",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.508,
    "lon": 4.372,
    "photo": "Balazuc Ardeche village river",
    "desc": "Prachtig dorp tegen de rotswand, met zwemmen in de Ardèche. Heel geschikt als rustige halve dag.",
    "link": "https://www.google.com/search?q=Balazuc+Ardeche+rivierstrand",
    "id": "a005",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.508,4.372",
    "photo_url": "https://source.unsplash.com/800x520/?Balazuc%20Ardeche%20village%20river",
    "top": true,
    "mainCat": "water",
    "combine": [
      "Balazuc + rivierstrand",
      "Vogüé dorp en kasteel",
      "Lanas rivierstrand"
    ],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Vogüé dorp en kasteel",
    "type": [
      "Dorpjes",
      "Cultuur",
      "Zwemmen"
    ],
    "age": 0,
    "height": "",
    "drive": 20,
    "duration": "Halve dag",
    "distance": "2-4 km",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.551,
    "lon": 4.414,
    "photo": "Vogue Ardeche village castle",
    "desc": "Mooi dorp aan de rivier met kasteel, strandje en fotogenieke straatjes.",
    "link": "https://www.google.com/search?q=Vog%C3%BC%C3%A9+Ardeche+kasteel",
    "id": "a006",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.551,4.414",
    "photo_url": "https://source.unsplash.com/800x520/?Vogue%20Ardeche%20village%20castle",
    "top": true,
    "mainCat": "water",
    "combine": [
      "Balazuc + rivierstrand",
      "Vogüé dorp en kasteel",
      "Lanas rivierstrand"
    ],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Labeaume dorp + rotsen + rivier",
    "type": [
      "Dorpjes",
      "Zwemmen",
      "Wandelen"
    ],
    "age": 0,
    "height": "",
    "drive": 15,
    "duration": "Halve dag",
    "distance": "2-4 km",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.448,
    "lon": 4.309,
    "photo": "Labeaume Ardeche river rocks",
    "desc": "Een van de leukste plekken met kinderen: straatjes, rivier, rotsen en kleine strandjes.",
    "link": "https://www.google.com/search?q=Labeaume+Ardeche",
    "id": "a007",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.448,4.309",
    "photo_url": "https://source.unsplash.com/800x520/?Labeaume%20Ardeche%20river%20rocks",
    "top": true,
    "mainCat": "water",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Pradons avondwandeling",
    "type": [
      "Wandelen",
      "Dichtbij",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 2,
    "duration": "1 uur",
    "distance": "2-3 km",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.474,
    "lon": 4.36,
    "photo": "Pradons Ardeche",
    "desc": "Voor een rustige avond: klein rondje in/om Pradons, zonder grote excursie.",
    "link": "https://www.google.com/search?q=Pradons+Ardeche+wandelen",
    "id": "a008",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.474,4.36",
    "photo_url": "https://source.unsplash.com/800x520/?Pradons%20Ardeche",
    "top": false,
    "mainCat": "walk",
    "combine": [],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Pont d'Arc uitzicht + zwemmen",
    "type": [
      "Water",
      "Uitzicht",
      "Iconisch"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "1-3 km",
    "difficulty": 1,
    "cost": "Gratis/parkeren",
    "heat": true,
    "rain": false,
    "lat": 44.381,
    "lon": 4.416,
    "photo": "Pont d'Arc Ardeche",
    "desc": "Dé klassieker. Ga vroeg of eind middag voor minder drukte en mooier licht.",
    "link": "https://www.gorges-ardeche-pontdarc.fr/",
    "id": "a009",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.381,4.416",
    "photo_url": "https://source.unsplash.com/800x520/?Pont%20d'Arc%20Ardeche",
    "top": true,
    "mainCat": "water",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Route des Gorges uitzichtpunten",
    "type": [
      "Uitzicht",
      "Autoroute",
      "Foto"
    ],
    "age": 0,
    "height": "",
    "drive": 30,
    "duration": "Halve dag",
    "distance": "auto + korte stops",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": true,
    "lat": 44.342,
    "lon": 4.482,
    "photo": "Gorges de l'Ardeche viewpoints",
    "desc": "Met de auto langs meerdere belvédères boven de kloof. Ook fijn als niet iedereen wil wandelen.",
    "link": "https://www.google.com/search?q=Route+Touristique+des+Gorges+de+l%27Ard%C3%A8che+belv%C3%A9d%C3%A8res",
    "id": "a010",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.342,4.482",
    "photo_url": "https://source.unsplash.com/800x520/?Gorges%20de%20l'Ardeche%20viewpoints",
    "top": true,
    "mainCat": "walk",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Kano Ardèche 6-8 km",
    "type": [
      "Kano",
      "Water",
      "Actief"
    ],
    "age": 6,
    "height": "Zwemvaardig; eisen per verhuurder",
    "drive": 5,
    "duration": "Halve dag",
    "distance": "6-8 km varen",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "canoe Ardeche family",
    "desc": "Kortere kano-afdaling is meestal leuker met kinderen dan meteen de lange kloofroute.",
    "link": "https://www.google.com/search?q=canoe+Ardeche+Ruoms+6+km",
    "id": "a011",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?canoe%20Ardeche%20family",
    "top": true,
    "mainCat": "water",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Kano Vallon-Pont-d'Arc naar Châmes",
    "type": [
      "Kano",
      "Water",
      "Iconisch"
    ],
    "age": 7,
    "height": "Zwemvaardig; eisen per verhuurder",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "mini-afdaling",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.407,
    "lon": 4.394,
    "photo": "canoe Pont d'Arc family",
    "desc": "Leuk als je onder/naast Pont d'Arc wilt varen zonder de hele 24-32 km te doen.",
    "link": "https://www.google.com/search?q=canoe+Vallon+Pont+d%27Arc+mini+descente",
    "id": "a012",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.394",
    "photo_url": "https://source.unsplash.com/800x520/?canoe%20Pont%20d'Arc%20family",
    "top": false,
    "mainCat": "water",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Kano Gorges de l'Ardèche 24-32 km",
    "type": [
      "Kano",
      "Water",
      "Volwassenen"
    ],
    "age": 12,
    "height": "Goede conditie, zwemvaardig",
    "drive": 25,
    "duration": "Hele dag",
    "distance": "24-32 km varen",
    "difficulty": 4,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.407,
    "lon": 4.394,
    "photo": "Gorges de l'Ardeche canoe",
    "desc": "Fantastisch, maar lang en intensief. Eerder iets voor volwassenen/tieners dan voor Kato/Rover.",
    "link": "https://www.google.com/search?q=descente+Gorges+de+l%27Ard%C3%A8che+24+32+km+canoe",
    "id": "a013",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.394",
    "photo_url": "https://source.unsplash.com/800x520/?Gorges%20de%20l'Ardeche%20canoe",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "SUP op rustige rivierstukken",
    "type": [
      "SUP",
      "Water",
      "Relax"
    ],
    "age": 8,
    "height": "Zwemvaardig",
    "drive": 10,
    "duration": "1-2 uur",
    "distance": "variabel",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "stand up paddle Ardeche river",
    "desc": "Mooi alternatief voor kanoën als je rustig bij Ruoms/Balazuc wilt blijven.",
    "link": "https://www.google.com/search?q=SUP+Ardeche+Ruoms",
    "id": "a014",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?stand%20up%20paddle%20Ardeche%20river",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Plage de Sauze / Saint-Martin-d'Ardèche",
    "type": [
      "Zwemmen",
      "Water",
      "Dorpjes"
    ],
    "age": 0,
    "height": "",
    "drive": 60,
    "duration": "Hele dag",
    "distance": "stranddag",
    "difficulty": 1,
    "cost": "Gratis/parkeren",
    "heat": true,
    "rain": false,
    "lat": 44.304,
    "lon": 4.566,
    "photo": "Saint Martin d'Ardeche beach",
    "desc": "Verder rijden, maar mooi voor een dag aan het zuidelijke einde van de Gorges.",
    "link": "https://www.google.com/search?q=Saint-Martin-d%27Ard%C3%A8che+plage+Sauze",
    "id": "a015",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.304,4.566",
    "photo_url": "https://source.unsplash.com/800x520/?Saint%20Martin%20d'Ardeche%20beach",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "Grotte Chauvet 2",
    "type": [
      "Grot",
      "Cultuur",
      "Regen"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.407,
    "lon": 4.415,
    "photo": "Chauvet 2 Ardeche cave",
    "desc": "Replica van de beroemde prehistorische grot. Goede keuze bij hitte of regen.",
    "link": "https://www.grottechauvet2ardeche.com/",
    "id": "a016",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.415",
    "photo_url": "https://source.unsplash.com/800x520/?Chauvet%202%20Ardeche%20cave",
    "top": true,
    "mainCat": "indoor",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Aven d'Orgnac",
    "type": [
      "Grot",
      "Cultuur",
      "Regen"
    ],
    "age": 5,
    "height": "Veel trappen",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "binnen",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.316,
    "lon": 4.433,
    "photo": "Aven d'Orgnac cave",
    "desc": "Indrukwekkende druipsteengrot met grote zalen. Let op: trappen.",
    "link": "https://www.orgnac.com/",
    "id": "a017",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.316,4.433",
    "photo_url": "https://source.unsplash.com/800x520/?Aven%20d'Orgnac%20cave",
    "top": true,
    "mainCat": "indoor",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "Grotte de la Cocalière",
    "type": [
      "Grot",
      "Regen",
      "Cultuur"
    ],
    "age": 4,
    "height": "",
    "drive": 45,
    "duration": "Halve dag",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.269,
    "lon": 4.178,
    "photo": "Grotte de la Cocaliere",
    "desc": "Mooie grot, vaak leuk voor kinderen door de trein/terugrit-ervaring.",
    "link": "https://www.grotte-cocaliere.com/",
    "id": "a018",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.269,4.178",
    "photo_url": "https://source.unsplash.com/800x520/?Grotte%20de%20la%20Cocaliere",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "Grotte de Saint-Marcel",
    "type": [
      "Grot",
      "Regen",
      "Cultuur"
    ],
    "age": 4,
    "height": "",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.329,
    "lon": 4.542,
    "photo": "Grotte Saint Marcel Ardeche",
    "desc": "Grote grot met bijzondere bassins. Combineerbaar met route door de Gorges.",
    "link": "https://www.google.com/search?q=Grotte+Saint+Marcel+Ardeche",
    "id": "a019",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.329,4.542",
    "photo_url": "https://source.unsplash.com/800x520/?Grotte%20Saint%20Marcel%20Ardeche",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "Musée de la Lavande",
    "type": [
      "Cultuur",
      "Regen",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 35,
    "duration": "1-2 uur",
    "distance": "binnen/buiten",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.395,
    "lon": 4.508,
    "photo": "lavender museum Ardeche",
    "desc": "Rustige activiteit voor een hete of druilerige middag.",
    "link": "https://www.google.com/search?q=Mus%C3%A9e+de+la+Lavande+Ard%C3%A8che",
    "id": "a020",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.395,4.508",
    "photo_url": "https://source.unsplash.com/800x520/?lavender%20museum%20Ardeche",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Muséum de l'Ardèche",
    "type": [
      "Museum",
      "Regen",
      "Kindvriendelijk"
    ],
    "age": 5,
    "height": "",
    "drive": 20,
    "duration": "1-2 uur",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.53,
    "lon": 4.397,
    "photo": "fossil museum Ardeche",
    "desc": "Fossielen/dino-achtige vondsten; handig als het weer omslaat.",
    "link": "https://www.google.com/search?q=Mus%C3%A9um+de+l%27Ard%C3%A8che+Balazuc",
    "id": "a021",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.53,4.397",
    "photo_url": "https://source.unsplash.com/800x520/?fossil%20museum%20Ardeche",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Accroche Toi aux Branches",
    "type": [
      "Klimbos",
      "Avontuur",
      "Kindvriendelijk"
    ],
    "age": 3,
    "height": "Parcours verschilt per lengte",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "klimbos",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.404,
    "lon": 4.393,
    "photo": "accrobranche Ardeche family",
    "desc": "Klimbos bij Vallon-Pont-d'Arc met parcours voor verschillende leeftijden/lengtes.",
    "link": "https://www.google.com/search?q=Accroche+Toi+aux+Branches+Vallon+Pont+d%27Arc",
    "id": "a022",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.404,4.393",
    "photo_url": "https://source.unsplash.com/800x520/?accrobranche%20Ardeche%20family",
    "top": true,
    "mainCat": "adventure",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Indy Parc / Accrobranche bij Grospierres",
    "type": [
      "Klimbos",
      "Avontuur",
      "Kindvriendelijk"
    ],
    "age": 4,
    "height": "Parcours verschilt per lengte",
    "drive": 20,
    "duration": "Halve dag",
    "distance": "klimbos",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.4,
    "lon": 4.286,
    "photo": "tree climbing park Ardeche",
    "desc": "Nog een klimbosoptie; check actuele minimumlengtes per parcours.",
    "link": "https://www.google.com/search?q=Indy+Parc+Grospierres+accrobranche",
    "id": "a023",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.4,4.286",
    "photo_url": "https://source.unsplash.com/800x520/?tree%20climbing%20park%20Ardeche",
    "top": false,
    "mainCat": "adventure",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Via Ferrata Pont du Diable - begeleiding",
    "type": [
      "Via ferrata",
      "Avontuur",
      "Tieners"
    ],
    "age": 10,
    "height": "Vaak 1,35-1,40 m; soms 40 kg",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "2 uur activiteit",
    "difficulty": 3,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.675,
    "lon": 4.218,
    "photo": "Pont du Diable Thueyts via ferrata",
    "desc": "Mooie via ferrata met bruggen/tyrolienne. Geschikter voor Tibbe/Jens/Lize en volwassenen dan voor Kato/Rover.",
    "link": "https://ardeche-naturae.fr/via-ferrata/",
    "id": "a024",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.675,4.218",
    "photo_url": "https://source.unsplash.com/800x520/?Pont%20du%20Diable%20Thueyts%20via%20ferrata",
    "top": true,
    "mainCat": "adventure",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Via Ferrata Pont du Diable - sportiever",
    "type": [
      "Via ferrata",
      "Avontuur",
      "Volwassenen"
    ],
    "age": 12,
    "height": "Vaak 1,40 m en 40 kg",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "2-3 uur",
    "difficulty": 4,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.675,
    "lon": 4.218,
    "photo": "via ferrata ardeche bridge",
    "desc": "Tweede deel/varianten kunnen mentaal en fysiek pittiger zijn; mooi voor jou alleen of met tieners.",
    "link": "https://www.google.com/search?q=Via+Ferrata+Pont+du+Diable+Thueyts+1m40+40kg",
    "id": "a025",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.675,4.218",
    "photo_url": "https://source.unsplash.com/800x520/?via%20ferrata%20ardeche%20bridge",
    "top": false,
    "mainCat": "adventure",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Via Corda Aven d'Orgnac",
    "type": [
      "Via corda",
      "Avontuur",
      "Tieners"
    ],
    "age": 12,
    "height": "Check aanbieder",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "touwroute",
    "difficulty": 3,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.316,
    "lon": 4.433,
    "photo": "via corda Aven d'Orgnac",
    "desc": "Avontuurlijker alternatief rond de grot/rotsen. Check leeftijd/lengte bij aanbieder.",
    "link": "https://www.google.com/search?q=Via+Corda+Aven+d%27Orgnac",
    "id": "a026",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.316,4.433",
    "photo_url": "https://source.unsplash.com/800x520/?via%20corda%20Aven%20d'Orgnac",
    "top": false,
    "mainCat": "adventure",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "Canyoning familievariant Ardèche",
    "type": [
      "Canyoning",
      "Water",
      "Avontuur"
    ],
    "age": 8,
    "height": "Zwemvaardig; eisen per aanbieder",
    "drive": 30,
    "duration": "Halve dag",
    "distance": "kloof",
    "difficulty": 3,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.42,
    "lon": 4.25,
    "photo": "canyoning ardeche family",
    "desc": "Natuurlijke glijbanen, kleine sprongen en water. Vraag expliciet naar familieparcours.",
    "link": "https://www.google.com/search?q=canyoning+famille+Ard%C3%A8che+Ruoms",
    "id": "a027",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.42,4.25",
    "photo_url": "https://source.unsplash.com/800x520/?canyoning%20ardeche%20family",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Outdoor aanbieders"
  },
  {
    "title": "Canyoning sportief",
    "type": [
      "Canyoning",
      "Water",
      "Volwassenen"
    ],
    "age": 12,
    "height": "Goed zwemmen; check aanbieder",
    "drive": 45,
    "duration": "Halve dag/hele dag",
    "distance": "kloof",
    "difficulty": 4,
    "cost": "Betaald",
    "heat": true,
    "rain": false,
    "lat": 44.55,
    "lon": 4.15,
    "photo": "sport canyoning Ardeche",
    "desc": "Voor volwassenen/tieners die echt uitdaging willen. Niet voor de jongste kinderen.",
    "link": "https://www.google.com/search?q=canyoning+sportif+Ard%C3%A8che",
    "id": "a028",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.55,4.15",
    "photo_url": "https://source.unsplash.com/800x520/?sport%20canyoning%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Outdoor aanbieders"
  },
  {
    "title": "Speleologie familie",
    "type": [
      "Speleo",
      "Avontuur",
      "Regen"
    ],
    "age": 6,
    "height": "Check aanbieder",
    "drive": 30,
    "duration": "Halve dag",
    "distance": "ondergronds",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.407,
    "lon": 4.415,
    "photo": "speleology Ardeche family",
    "desc": "Leuk bij hitte of regen: kruipen/ontdekken onder begeleiding. Vraag naar kinderroute.",
    "link": "https://www.google.com/search?q=sp%C3%A9l%C3%A9ologie+famille+Ard%C3%A8che+Vallon+Pont+d%27Arc",
    "id": "a029",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.415",
    "photo_url": "https://source.unsplash.com/800x520/?speleology%20Ardeche%20family",
    "top": false,
    "mainCat": "adventure",
    "combine": [],
    "region": "Outdoor aanbieders"
  },
  {
    "title": "Bois de Païolive - Sentier de la Vierge",
    "type": [
      "Wandelen",
      "Schaduw",
      "Klauteren"
    ],
    "age": 5,
    "height": "",
    "drive": 30,
    "duration": "1-2 uur",
    "distance": "2-4 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.376,
    "lon": 4.213,
    "photo": "Bois de Paiolive Ardeche rocks",
    "desc": "Sprookjesachtig bos met kalksteenrotsen. Veel schaduw en klauterpret.",
    "link": "https://www.google.com/search?q=Bois+de+Pa%C3%AFolive+sentier+de+la+Vierge",
    "id": "a030",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.376,4.213",
    "photo_url": "https://source.unsplash.com/800x520/?Bois%20de%20Paiolive%20Ardeche%20rocks",
    "top": true,
    "mainCat": "walk",
    "combine": [
      "Bois de Païolive - Sentier de la Vierge",
      "Chassezac rivierstrand Casteljau",
      "Naves en Les Vans"
    ],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Bois de Païolive - Corniche du Chassezac",
    "type": [
      "Wandelen",
      "Uitzicht",
      "Klauteren"
    ],
    "age": 8,
    "height": "",
    "drive": 30,
    "duration": "2 uur",
    "distance": "4-5 km",
    "difficulty": 3,
    "cost": "Gratis",
    "heat": false,
    "rain": false,
    "lat": 44.376,
    "lon": 4.213,
    "photo": "Chassezac gorge viewpoint",
    "desc": "Mooier uitzicht maar iets serieuzer dan de makkelijkste bosroute.",
    "link": "https://www.google.com/search?q=Corniche+du+Chassezac+Bois+de+Pa%C3%AFolive",
    "id": "a031",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.376,4.213",
    "photo_url": "https://source.unsplash.com/800x520/?Chassezac%20gorge%20viewpoint",
    "top": false,
    "mainCat": "walk",
    "combine": [
      "Bois de Païolive - Sentier de la Vierge",
      "Chassezac rivierstrand Casteljau",
      "Naves en Les Vans"
    ],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Gorges du Chassezac korte wandeling",
    "type": [
      "Wandelen",
      "Zwemmen",
      "Uitzicht"
    ],
    "age": 6,
    "height": "",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "3-5 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.395,
    "lon": 4.185,
    "photo": "Gorges du Chassezac Ardeche",
    "desc": "Mooie kloof met zwemplekken; check routekeuze op lengte/veiligheid.",
    "link": "https://www.google.com/search?q=Gorges+du+Chassezac+wandeling+kort",
    "id": "a032",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.395,4.185",
    "photo_url": "https://source.unsplash.com/800x520/?Gorges%20du%20Chassezac%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [
      "Bois de Païolive - Sentier de la Vierge",
      "Chassezac rivierstrand Casteljau",
      "Naves en Les Vans"
    ],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Dent de Rez",
    "type": [
      "Wandelen",
      "Trailrun",
      "Uitzicht"
    ],
    "age": 12,
    "height": "",
    "drive": 45,
    "duration": "Halve dag",
    "distance": "5-8 km",
    "difficulty": 4,
    "cost": "Gratis",
    "heat": false,
    "rain": false,
    "lat": 44.436,
    "lon": 4.521,
    "photo": "Dent de Rez Ardeche",
    "desc": "Voor jou of met fitte tieners: stevige klim met groots uitzicht. Vroeg starten bij hitte.",
    "link": "https://www.google.com/search?q=Dent+de+Rez+randonn%C3%A9e",
    "id": "a033",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.436,4.521",
    "photo_url": "https://source.unsplash.com/800x520/?Dent%20de%20Rez%20Ardeche",
    "top": false,
    "mainCat": "sport",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Rochecolombe + waterval",
    "type": [
      "Wandelen",
      "Waterval",
      "Dorpjes"
    ],
    "age": 5,
    "height": "",
    "drive": 25,
    "duration": "1-2 uur",
    "distance": "2-4 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.518,
    "lon": 4.431,
    "photo": "Rochecolombe cascade Ardeche",
    "desc": "Mooi oud dorp en intermittente waterval; stroming/water hangt af van seizoen.",
    "link": "https://www.google.com/search?q=Rochecolombe+cascade+Ard%C3%A8che",
    "id": "a034",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.518,4.431",
    "photo_url": "https://source.unsplash.com/800x520/?Rochecolombe%20cascade%20Ardeche",
    "top": true,
    "mainCat": "water",
    "combine": [],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Cascade de Pissevieille",
    "type": [
      "Wandelen",
      "Waterval",
      "Natuur"
    ],
    "age": 8,
    "height": "",
    "drive": 25,
    "duration": "1-2 uur",
    "distance": "2-4 km",
    "difficulty": 3,
    "cost": "Gratis",
    "heat": false,
    "rain": false,
    "lat": 44.395,
    "lon": 4.449,
    "photo": "Cascade de Pissevieille Ardeche",
    "desc": "Waterval bij Vallon; vooral mooi na regen. Route kan glad/rotsig zijn.",
    "link": "https://www.google.com/search?q=Cascade+de+Pissevieille+Vallon+Pont+d%27Arc",
    "id": "a035",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.395,4.449",
    "photo_url": "https://source.unsplash.com/800x520/?Cascade%20de%20Pissevieille%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Vallon de l'Ibie korte wandeling/zwemmen",
    "type": [
      "Wandelen",
      "Zwemmen",
      "Natuur"
    ],
    "age": 5,
    "height": "",
    "drive": 30,
    "duration": "Halve dag",
    "distance": "2-5 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.45,
    "lon": 4.5,
    "photo": "Vallon de l'Ibie Ardeche",
    "desc": "Rustiger riviergebied met mooie poelen als er water staat. Perfect voor half dagje natuur.",
    "link": "https://www.google.com/search?q=Vallon+de+l%27Ibie+baignade",
    "id": "a036",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.45,4.5",
    "photo_url": "https://source.unsplash.com/800x520/?Vallon%20de%20l'Ibie%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Jaujac coulée basaltique",
    "type": [
      "Wandelen",
      "Geologie",
      "Zwemmen"
    ],
    "age": 5,
    "height": "",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "2-5 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.637,
    "lon": 4.256,
    "photo": "Jaujac basalt Ardeche",
    "desc": "Basaltformaties en rivier: leuk anders landschap. Combineer met dorpje Jaujac.",
    "link": "https://www.google.com/search?q=Jaujac+coul%C3%A9e+basaltique",
    "id": "a037",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.637,4.256",
    "photo_url": "https://source.unsplash.com/800x520/?Jaujac%20basalt%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Joyeuse markt en oude stad",
    "type": [
      "Dorpjes",
      "Markt",
      "Eten"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.479,
    "lon": 4.238,
    "photo": "Joyeuse Ardeche market",
    "desc": "Leuk markt-/dorpjesuitje met winkeltjes en terrassen.",
    "link": "https://www.google.com/search?q=Joyeuse+Ardeche+market",
    "id": "a040",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.479,4.238",
    "photo_url": "https://source.unsplash.com/800x520/?Joyeuse%20Ardeche%20market",
    "top": true,
    "mainCat": "culture",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Vallon-Pont-d'Arc avondmarkt/centrum",
    "type": [
      "Dorpjes",
      "Markt",
      "Eten"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "1-3 uur",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.407,
    "lon": 4.394,
    "photo": "Vallon Pont d'Arc village",
    "desc": "Toeristisch maar gezellig: eten, ijs, souvenirwinkels, activiteit boeken.",
    "link": "https://www.google.com/search?q=Vallon+Pont+d%27Arc+march%C3%A9+nocturne",
    "id": "a041",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.394",
    "photo_url": "https://source.unsplash.com/800x520/?Vallon%20Pont%20d'Arc%20village",
    "top": true,
    "mainCat": "culture",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Aubenas kasteel en stad",
    "type": [
      "Stad",
      "Cultuur",
      "Regen"
    ],
    "age": 0,
    "height": "",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.62,
    "lon": 4.389,
    "photo": "Aubenas Ardeche castle",
    "desc": "Grotere stad voor markt, winkels, kasteel en terras. Ook handig als het weer minder is.",
    "link": "https://www.google.com/search?q=Aubenas+ch%C3%A2teau+visiter",
    "id": "a042",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.62,4.389",
    "photo_url": "https://source.unsplash.com/800x520/?Aubenas%20Ardeche%20castle",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Naves en Les Vans",
    "type": [
      "Dorpjes",
      "Markt",
      "Eten"
    ],
    "age": 0,
    "height": "",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": true,
    "lat": 44.405,
    "lon": 4.133,
    "photo": "Les Vans Ardeche village",
    "desc": "Leuke combinatie met Bois de Païolive of Chassezac.",
    "link": "https://www.google.com/search?q=Les+Vans+Naves+Ard%C3%A8che",
    "id": "a043",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.405,4.133",
    "photo_url": "https://source.unsplash.com/800x520/?Les%20Vans%20Ardeche%20village",
    "top": false,
    "mainCat": "culture",
    "combine": [
      "Bois de Païolive - Sentier de la Vierge",
      "Chassezac rivierstrand Casteljau",
      "Naves en Les Vans"
    ],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Banne karakterdorp",
    "type": [
      "Dorpjes",
      "Uitzicht",
      "Cultuur"
    ],
    "age": 0,
    "height": "",
    "drive": 40,
    "duration": "Halve dag",
    "distance": "2-3 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": false,
    "rain": true,
    "lat": 44.366,
    "lon": 4.157,
    "photo": "Banne Ardeche village",
    "desc": "Mooi dorp met ruïne/uitzicht. Fijn voor een rustigere halve dag.",
    "link": "https://www.google.com/search?q=Banne+village+Ard%C3%A8che",
    "id": "a044",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.366,4.157",
    "photo_url": "https://source.unsplash.com/800x520/?Banne%20Ardeche%20village",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Antraigues-sur-Volane",
    "type": [
      "Dorpjes",
      "Autoroute",
      "Eten"
    ],
    "age": 0,
    "height": "",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": true,
    "lat": 44.719,
    "lon": 4.358,
    "photo": "Antraigues sur Volane Ardeche",
    "desc": "Charmant bergdorp; combineer met mooie route door het binnenland.",
    "link": "https://www.google.com/search?q=Antraigues-sur-Volane",
    "id": "a045",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.719,4.358",
    "photo_url": "https://source.unsplash.com/800x520/?Antraigues%20sur%20Volane%20Ardeche",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Alba-la-Romaine",
    "type": [
      "Dorpjes",
      "Cultuur",
      "Historie"
    ],
    "age": 0,
    "height": "",
    "drive": 35,
    "duration": "Halve dag",
    "distance": "2-4 km",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": false,
    "rain": true,
    "lat": 44.554,
    "lon": 4.599,
    "photo": "Alba la Romaine Ardeche",
    "desc": "Mooi dorp plus Romeinse archeologie. Leuk als cultuurdag.",
    "link": "https://www.google.com/search?q=Alba-la-Romaine+Ard%C3%A8che+site+antique",
    "id": "a046",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.554,4.599",
    "photo_url": "https://source.unsplash.com/800x520/?Alba%20la%20Romaine%20Ardeche",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Viviers oude stad",
    "type": [
      "Dorpjes",
      "Cultuur",
      "Historie"
    ],
    "age": 0,
    "height": "",
    "drive": 45,
    "duration": "Halve dag",
    "distance": "2-4 km",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": false,
    "rain": true,
    "lat": 44.482,
    "lon": 4.688,
    "photo": "Viviers Ardeche old town",
    "desc": "Minder standaard maar prachtig oud stadje aan de Rhône.",
    "link": "https://www.google.com/search?q=Viviers+Ard%C3%A8che+visiter",
    "id": "a047",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.482,4.688",
    "photo_url": "https://source.unsplash.com/800x520/?Viviers%20Ardeche%20old%20town",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Chassezac rivierstrand Casteljau",
    "type": [
      "Zwemmen",
      "Water",
      "Picknick"
    ],
    "age": 0,
    "height": "",
    "drive": 30,
    "duration": "Halve dag",
    "distance": "strand",
    "difficulty": 1,
    "cost": "Gratis/parkeren",
    "heat": true,
    "rain": false,
    "lat": 44.394,
    "lon": 4.187,
    "photo": "Chassezac swimming Casteljau",
    "desc": "Fijn alternatief voor de Ardèche: rivierstrandjes en rotsen.",
    "link": "https://www.google.com/search?q=Casteljau+Chassezac+baignade",
    "id": "a048",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.394,4.187",
    "photo_url": "https://source.unsplash.com/800x520/?Chassezac%20swimming%20Casteljau",
    "top": true,
    "mainCat": "water",
    "combine": [
      "Bois de Païolive - Sentier de la Vierge",
      "Chassezac rivierstrand Casteljau",
      "Naves en Les Vans"
    ],
    "region": "Païolive / Chassezac / Les Vans"
  },
  {
    "title": "Lanas rivierstrand",
    "type": [
      "Zwemmen",
      "Water",
      "Dichtbij"
    ],
    "age": 0,
    "height": "",
    "drive": 15,
    "duration": "Halve dag",
    "distance": "strand",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.535,
    "lon": 4.395,
    "photo": "Lanas Ardeche river beach",
    "desc": "Kleine zwemplek aan de Ardèche; combineerbaar met Balazuc/Vogüé.",
    "link": "https://www.google.com/search?q=Lanas+Ard%C3%A8che+baignade",
    "id": "a049",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.535,4.395",
    "photo_url": "https://source.unsplash.com/800x520/?Lanas%20Ardeche%20river%20beach",
    "top": false,
    "mainCat": "water",
    "combine": [
      "Balazuc + rivierstrand",
      "Vogüé dorp en kasteel",
      "Lanas rivierstrand"
    ],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Rivière Beaume bij Labeaume",
    "type": [
      "Zwemmen",
      "Water",
      "Dorpjes"
    ],
    "age": 0,
    "height": "",
    "drive": 15,
    "duration": "Halve dag",
    "distance": "strand/rotsen",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.448,
    "lon": 4.309,
    "photo": "Labeaume river swimming",
    "desc": "Mooi zwemmen en klauteren bij Labeaume. Waterschoenen handig.",
    "link": "https://www.google.com/search?q=Labeaume+baignade+rivi%C3%A8re",
    "id": "a050",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.448,4.309",
    "photo_url": "https://source.unsplash.com/800x520/?Labeaume%20river%20swimming",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Pont du Diable zwemmen bij Thueyts",
    "type": [
      "Zwemmen",
      "Water",
      "Uitzicht"
    ],
    "age": 6,
    "height": "",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "afdalen naar rivier",
    "difficulty": 2,
    "cost": "Gratis/parkeren",
    "heat": true,
    "rain": false,
    "lat": 44.675,
    "lon": 4.218,
    "photo": "Pont du Diable Thueyts swimming",
    "desc": "Mooi zwemgebied onder de brug; combineerbaar met via ferrata voor anderen.",
    "link": "https://www.google.com/search?q=Pont+du+Diable+Thueyts+baignade",
    "id": "a051",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.675,4.218",
    "photo_url": "https://source.unsplash.com/800x520/?Pont%20du%20Diable%20Thueyts%20swimming",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Cascade du Ray-Pic",
    "type": [
      "Waterval",
      "Wandelen",
      "Hele dag"
    ],
    "age": 5,
    "height": "",
    "drive": 90,
    "duration": "Hele dag",
    "distance": "korte wandeling",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.774,
    "lon": 4.294,
    "photo": "Cascade du Ray Pic Ardeche",
    "desc": "Spectaculaire waterval, maar ver rijden. Mooi als dagtrip naar de bergen.",
    "link": "https://www.google.com/search?q=Cascade+du+Ray+Pic+Ard%C3%A8che",
    "id": "a052",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.774,4.294",
    "photo_url": "https://source.unsplash.com/800x520/?Cascade%20du%20Ray%20Pic%20Ardeche",
    "top": false,
    "mainCat": "water",
    "combine": [],
    "region": "Bergen / Noord-Ardèche"
  },
  {
    "title": "Parc Animalier de Lussas",
    "type": [
      "Dieren",
      "Kindvriendelijk",
      "Halve dag"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "Halve dag",
    "distance": "wandelen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.608,
    "lon": 4.471,
    "photo": "animal park Ardeche family",
    "desc": "Dierenpark/kinderuitje als afwisseling van zwemmen en wandelen.",
    "link": "https://www.google.com/search?q=Parc+animalier+Lussas+Ard%C3%A8che",
    "id": "a054",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.608,4.471",
    "photo_url": "https://source.unsplash.com/800x520/?animal%20park%20Ardeche%20family",
    "top": false,
    "mainCat": "walk",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Aven Marzal zoo préhistorique",
    "type": [
      "Dieren",
      "Grot",
      "Kindvriendelijk"
    ],
    "age": 4,
    "height": "",
    "drive": 55,
    "duration": "Halve dag",
    "distance": "park",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.333,
    "lon": 4.549,
    "photo": "Aven Marzal zoo prehistorique",
    "desc": "Combinatie van grot/prehistorische dieren; toeristisch maar leuk voor kinderen.",
    "link": "https://www.google.com/search?q=Aven+Marzal+zoo+prehistorique",
    "id": "a055",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.333,4.549",
    "photo_url": "https://source.unsplash.com/800x520/?Aven%20Marzal%20zoo%20prehistorique",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Grotten / Zuid-Ardèche"
  },
  {
    "title": "La Ferme aux Crocodiles",
    "type": [
      "Dieren",
      "Regen",
      "Hele dag"
    ],
    "age": 0,
    "height": "",
    "drive": 60,
    "duration": "Halve dag/hele dag",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.333,
    "lon": 4.756,
    "photo": "Ferme aux Crocodiles Pierrelatte",
    "desc": "Verder weg maar heel handig bij regen of extreme hitte.",
    "link": "https://www.lafermeauxcrocodiles.com/",
    "id": "a056",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.333,4.756",
    "photo_url": "https://source.unsplash.com/800x520/?Ferme%20aux%20Crocodiles%20Pierrelatte",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Via Ardèche richting Vogüé",
    "type": [
      "Fietsen",
      "Kindvriendelijk",
      "Dorpjes"
    ],
    "age": 6,
    "height": "Zelfstandig fietsen",
    "drive": 15,
    "duration": "Halve dag",
    "distance": "zelf kiezen",
    "difficulty": 1,
    "cost": "Gratis/fietshuur",
    "heat": true,
    "rain": false,
    "lat": 44.551,
    "lon": 4.414,
    "photo": "Via Ardeche Vogue cycling",
    "desc": "Mooi stuk met dorpjes/viaducten. Voor jonge kinderen: kort houden.",
    "link": "https://via-ardeche.fr/itineraire/",
    "id": "a057",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.551,4.414",
    "photo_url": "https://source.unsplash.com/800x520/?Via%20Ardeche%20Vogue%20cycling",
    "top": false,
    "mainCat": "culture",
    "combine": [
      "Balazuc + rivierstrand",
      "Vogüé dorp en kasteel",
      "Lanas rivierstrand"
    ],
    "region": "Balazuc / Vogüé / Aubenas"
  },
  {
    "title": "Via Ardèche richting Grospierres",
    "type": [
      "Fietsen",
      "Kindvriendelijk",
      "Natuur"
    ],
    "age": 6,
    "height": "Zelfstandig fietsen",
    "drive": 15,
    "duration": "Halve dag",
    "distance": "zelf kiezen",
    "difficulty": 1,
    "cost": "Gratis/fietshuur",
    "heat": true,
    "rain": false,
    "lat": 44.4,
    "lon": 4.286,
    "photo": "voie verte ardeche greenway",
    "desc": "Goed alternatief voor technische mountainbike-routes. Minder stress met jonge fietsers.",
    "link": "https://via-ardeche.fr/",
    "id": "a058",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.4,4.286",
    "photo_url": "https://source.unsplash.com/800x520/?voie%20verte%20ardeche%20greenway",
    "top": false,
    "mainCat": "bike",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "MTB begeleide tocht volwassenen/tieners",
    "type": [
      "MTB",
      "Avontuur",
      "Tieners"
    ],
    "age": 12,
    "height": "Ervaring met schakelen/remmen",
    "drive": 20,
    "duration": "Halve dag",
    "distance": "variabel",
    "difficulty": 4,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "mountain biking Ardeche trails",
    "desc": "De officiële MTB-routes zijn vaak steenachtig/technisch. Geschikt voor Jens/Lize/volwassenen met ervaring.",
    "link": "https://www.google.com/search?q=VTT+Ard%C3%A8che+Ruoms+location+guide",
    "id": "a059",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?mountain%20biking%20Ardeche%20trails",
    "top": false,
    "mainCat": "adventure",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "E-bike route door Gorges de l'Ardèche",
    "type": [
      "Fietsen",
      "Uitzicht",
      "Volwassenen"
    ],
    "age": 14,
    "height": "Tieners/volwassenen",
    "drive": 25,
    "duration": "Halve dag/hele dag",
    "distance": "20-50 km",
    "difficulty": 3,
    "cost": "Betaald",
    "heat": false,
    "rain": false,
    "lat": 44.407,
    "lon": 4.394,
    "photo": "electric bike Gorges de l'Ardeche",
    "desc": "Voor volwassenen/oudere tieners: mooie route, maar in de zomer vroeg starten.",
    "link": "https://www.google.com/search?q=e-bike+Gorges+de+l%27Ard%C3%A8che",
    "id": "a060",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.394",
    "photo_url": "https://source.unsplash.com/800x520/?electric%20bike%20Gorges%20de%20l'Ardeche",
    "top": false,
    "mainCat": "bike",
    "combine": [],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Markt in Ruoms",
    "type": [
      "Markt",
      "Eten",
      "Dichtbij"
    ],
    "age": 0,
    "height": "",
    "drive": 7,
    "duration": "1-2 uur",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "Ruoms market Ardeche",
    "desc": "Voor fruit, brood, kaas, souvenirs en vakantiegevoel. Check actuele marktdag.",
    "link": "https://www.google.com/search?q=Ruoms+market+day+Ardeche",
    "id": "a061",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?Ruoms%20market%20Ardeche",
    "top": false,
    "mainCat": "culture",
    "combine": [
      "Cirque de Gens korte lus",
      "Ruoms oude centrum + ijsje",
      "Via Ardèche - stukje fietsen vanaf Ruoms"
    ],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Markt in Joyeuse",
    "type": [
      "Markt",
      "Eten",
      "Dorpjes"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "1-2 uur",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Gratis/betaald",
    "heat": true,
    "rain": true,
    "lat": 44.479,
    "lon": 4.238,
    "photo": "Joyeuse market Ardeche",
    "desc": "Gezellige markt en fijne combi met lunch/ijs.",
    "link": "https://www.google.com/search?q=Joyeuse+market+day",
    "id": "a062",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.479,4.238",
    "photo_url": "https://source.unsplash.com/800x520/?Joyeuse%20market%20Ardeche",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Avondijsje in Vallon-Pont-d'Arc",
    "type": [
      "Eten",
      "Dorpjes",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "1-2 uur",
    "distance": "slenteren",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.407,
    "lon": 4.394,
    "photo": "Vallon Pont d'Arc evening",
    "desc": "Geen groot plan nodig: na een warme dag even sfeer happen.",
    "link": "https://www.google.com/search?q=Vallon+Pont+d%27Arc+glacier",
    "id": "a063",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.407,4.394",
    "photo_url": "https://source.unsplash.com/800x520/?Vallon%20Pont%20d'Arc%20evening",
    "top": false,
    "mainCat": "culture",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Picknick bij een belvédère",
    "type": [
      "Uitzicht",
      "Eten",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 30,
    "duration": "1-2 uur",
    "distance": "korte stop",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.35,
    "lon": 4.48,
    "photo": "Ardeche gorges viewpoint picnic",
    "desc": "Koop lokaal lekkers en kies een uitzichtpunt langs de Gorges-route.",
    "link": "https://www.google.com/search?q=belv%C3%A9d%C3%A8res+Gorges+de+l%27Ard%C3%A8che",
    "id": "a064",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.35,4.48",
    "photo_url": "https://source.unsplash.com/800x520/?Ardeche%20gorges%20viewpoint%20picnic",
    "top": false,
    "mainCat": "culture",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Trailrun Cirque de Gens",
    "type": [
      "Trailrun",
      "Wandelen",
      "Sportief"
    ],
    "age": 14,
    "height": "Alleen ervaren lopers",
    "drive": 5,
    "duration": "1-2 uur",
    "distance": "6-10 km",
    "difficulty": 4,
    "cost": "Gratis",
    "heat": false,
    "rain": false,
    "lat": 44.489,
    "lon": 4.372,
    "photo": "trail running Ardeche cliffs",
    "desc": "Voor jou alleen: vroeg in de ochtend, prachtig licht, rotsen en uitzicht.",
    "link": "https://www.google.com/search?q=trail+Cirque+de+Gens+Ruoms",
    "id": "a065",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.489,4.372",
    "photo_url": "https://source.unsplash.com/800x520/?trail%20running%20Ardeche%20cliffs",
    "top": true,
    "mainCat": "sport",
    "combine": [
      "Cirque de Gens korte lus",
      "Ruoms oude centrum + ijsje",
      "Via Ardèche - stukje fietsen vanaf Ruoms"
    ],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Hardlopen Via Ardèche",
    "type": [
      "Trailrun",
      "Fietsen",
      "Dichtbij"
    ],
    "age": 12,
    "height": "",
    "drive": 8,
    "duration": "1 uur",
    "distance": "5-10 km",
    "difficulty": 2,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "greenway running Ardeche",
    "desc": "Veiliger en vlakker looprondje dan losse stenige paden. Ook geschikt als ochtendrun.",
    "link": "https://via-ardeche.fr/",
    "id": "a066",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?greenway%20running%20Ardeche",
    "top": false,
    "mainCat": "bike",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Zonsopgang Pont d'Arc",
    "type": [
      "Foto",
      "Uitzicht",
      "Relax"
    ],
    "age": 0,
    "height": "",
    "drive": 25,
    "duration": "1-2 uur",
    "distance": "korte wandeling",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": false,
    "lat": 44.381,
    "lon": 4.416,
    "photo": "Pont d'Arc sunrise",
    "desc": "Vroeg opstaan loont: rust, licht, minder hitte. Later ontbijten/zwemmen.",
    "link": "https://www.google.com/search?q=Pont+d%27Arc+sunrise",
    "id": "a067",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.381,4.416",
    "photo_url": "https://source.unsplash.com/800x520/?Pont%20d'Arc%20sunrise",
    "top": true,
    "mainCat": "walk",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  },
  {
    "title": "Zwembadcamping + spelletjesdag",
    "type": [
      "Relax",
      "Kindvriendelijk",
      "Dichtbij"
    ],
    "age": 0,
    "height": "",
    "drive": 0,
    "duration": "Halve dag",
    "distance": "0 km",
    "difficulty": 1,
    "cost": "Gratis",
    "heat": true,
    "rain": true,
    "lat": 44.482,
    "lon": 4.359,
    "photo": "camping pool family Ardeche",
    "desc": "Geen excursie, wel vakantie. Zwembad, boek, kaarten, boodschappen, vroeg eten.",
    "link": "https://www.campingdupontardeche.com/",
    "id": "a068",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.482,4.359",
    "photo_url": "https://source.unsplash.com/800x520/?camping%20pool%20family%20Ardeche",
    "top": false,
    "mainCat": "walk",
    "combine": [],
    "region": "Dichtbij camping / Ruoms"
  },
  {
    "title": "Boodschappen + kookavond thema Frans",
    "type": [
      "Eten",
      "Relax",
      "Regen"
    ],
    "age": 0,
    "height": "",
    "drive": 5,
    "duration": "Halve dag",
    "distance": "supermarkt/markt",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.452,
    "lon": 4.342,
    "photo": "French market picnic cheese bread",
    "desc": "Laat kinderen ieder iets kiezen: kaas, fruit, brood, dessert. Simpel maar vaak memorabel.",
    "link": "https://www.google.com/search?q=supermarket+Ruoms",
    "id": "a069",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.452,4.342",
    "photo_url": "https://source.unsplash.com/800x520/?French%20market%20picnic%20cheese%20bread",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Maison de l'Image / lokale expo",
    "type": [
      "Cultuur",
      "Regen",
      "Rustig"
    ],
    "age": 8,
    "height": "",
    "drive": 30,
    "duration": "1-2 uur",
    "distance": "binnen",
    "difficulty": 1,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.62,
    "lon": 4.39,
    "photo": "Ardeche art exhibition",
    "desc": "Voor een rustigere regenmiddag: check actuele exposities in Aubenas/Vallon.",
    "link": "https://www.google.com/search?q=exposition+Aubenas+Ard%C3%A8che",
    "id": "a070",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.62,4.39",
    "photo_url": "https://source.unsplash.com/800x520/?Ardeche%20art%20exhibition",
    "top": false,
    "mainCat": "indoor",
    "combine": [],
    "region": "Overig"
  },
  {
    "title": "Escape game Aubenas/Vallon",
    "type": [
      "Regen",
      "Spel",
      "Tieners"
    ],
    "age": 10,
    "height": "",
    "drive": 30,
    "duration": "1-2 uur",
    "distance": "binnen",
    "difficulty": 2,
    "cost": "Betaald",
    "heat": true,
    "rain": true,
    "lat": 44.62,
    "lon": 4.39,
    "photo": "escape room family",
    "desc": "Voor Lize/Jens/Tibbe en volwassenen als het weer tegenzit.",
    "link": "https://www.google.com/search?q=escape+game+Aubenas+Vallon+Pont+d%27Arc",
    "id": "a071",
    "maps": "https://www.google.com/maps/search/?api=1&query=44.62,4.39",
    "photo_url": "https://source.unsplash.com/800x520/?escape%20room%20family",
    "top": false,
    "mainCat": "indoor",
    "combine": [
      "Pont d'Arc uitzicht + zwemmen",
      "Grotte Chauvet 2",
      "Vallon-Pont-d'Arc avondmarkt/centrum"
    ],
    "region": "Pont d’Arc / Vallon"
  }
];
